[workspace]
members = [
    "coerce-rt",
    "coerce-remote",
#    "coerce-remote/providers/coerce-mysql",
    "coerce-remote/providers/coerce-redis",
    "coerce-remote/examples/coerce-chat-worker",
    "coerce-remote/examples/coerce-chat-gateway"
]
