[workspace]
members = [
    "coerce",
    "coerce/macros",
    "examples/coerce-cluster-example",
    "examples/coerce-sharded-chat-example",
    "coerce/tools/coerce-proto-build",
    "providers/persistence/coerce-redis",
    "providers/discovery/coerce-k8s"
]