[package]
name = "coerce-proto-build"
version = "0.1.0"
authors = ["Leon Hartley <ljph@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "3.2.0"
protobuf-codegen = "3.2.0"